spidermonkey: It requires cbindgen
Without cbindgen:

    ERROR: Cannot find cbindgen. Please run `mach bootstrap`,
    `cargo install cbindgen`, ensure that `cbindgen` is on your PATH,
    or point at an executable with `CBINDGEN`.

And I've found no way to work it around.